toolchain("aarch64-none-linux-gnu")
    set_kind("standalone")
    set_sdkdir("/home/asterich/code/cpp/embedded/gcc-arm-aarch64-linux-gnu/")
toolchain_end()


add_syslinks("c", "m")
add_requires("nlohmann_json")
add_requires("openssl", {system = false, plat = "cross", arch = "arm64-v8a", configs = {toolchains = "aarch64-none-linux-gnu"}})
add_requires("libcurl", {system = false, plat = "cross", arch = "arm64-v8a", configs = {toolchains = "aarch64-none-linux-gnu"}})
add_requires("utf8.h", {system = false, plat = "cross", arch = "arm64-v8a", configs = {toolchains = "aarch64-none-linux-gnu"}})

target("gomoku_server")
    set_kind("binary")
    add_files("*.c|gomoku_1p_with_ai.c|gomoku_client.c")
    remove_files("server.c", "client.c", "gui_press.c", "ui_design.c")
    add_files("$(projectdir)/../common/*.c")
    add_includedirs("$(projectdir)/../common/")
    add_includedirs("$(projectdir)/../common/external/include")
    add_links("asound", "jpeg", "freetype", "png", "z")
    add_linkdirs("$(projectdir)/../common/external/lib")
    set_toolchains("aarch64-none-linux-gnu")
    add_packages("utf8.h")
    after_build(function (target)
        os.mv(target:targetfile(), "../out/")
    end)

target("gomoku_client")
    set_kind("binary")
    add_files("*.c|gomoku_1p_with_ai.c|gomoku_server.c")
    remove_files("server.c", "client.c", "gui_press.c", "ui_design.c")
    add_files("$(projectdir)/../common/*.c")
    add_includedirs("$(projectdir)/../common/")
    add_includedirs("$(projectdir)/../common/external/include")
    add_links("asound", "jpeg", "freetype", "png", "z")
    add_linkdirs("$(projectdir)/../common/external/lib")
    set_toolchains("aarch64-none-linux-gnu")
    add_packages("utf8.h")
    after_build(function (target)
        os.mv(target:targetfile(), "../out/")
    end)

target("gomoku_1p_with_ai")
    set_kind("binary")
    add_files("*.c|gomoku_server.c|gomoku_client.c")
    remove_files("server.c", "client.c", "gui_press.c", "ui_design.c")
    add_files("gomoku_gpt.cpp")
    add_files("$(projectdir)/../common/*.c")
    add_includedirs("$(projectdir)/../common/")
    add_includedirs("$(projectdir)/../common/external/include")
    add_links("asound", "jpeg", "freetype", "png", "z")
    add_linkdirs("$(projectdir)/../common/external/lib")
    set_toolchains("aarch64-none-linux-gnu")
    add_packages("nlohmann_json")
    add_packages("openssl")
    add_packages("libcurl")
    add_packages("utf8.h")
    after_build(function (target)
        os.mv(target:targetfile(), "../out/")
    end)



    
    